version: "3.7"
services:
  telegram_bot:
    container_name: "telegram_bot"
    build:
      dockerfile: dockerfile
      context: ./telegram_bot
    env_file:
      - ./telegram_bot/.secret
    volumes:
      - ./build:/build
    network_mode: "host"